-- Rooms – bookable resources.
-- Migrations are plain SQL, applied in file-name order and recorded in `_sqlx_migrations`.
-- Never edit an applied migration (its checksum is verified) – add a new one instead.

CREATE TABLE rooms (
    id          UUID PRIMARY KEY,                 -- generated by the application (UUID v7)
    name        TEXT NOT NULL CHECK (char_length(name) BETWEEN 1 AND 100),
    description TEXT,
    capacity    INTEGER NOT NULL CHECK (capacity > 0),
    opens_at    TIME NOT NULL,
    closes_at   TIME NOT NULL,
    created_at  TIMESTAMPTZ NOT NULL DEFAULT now(),
    -- The database protects invariants too: the last line of defence for every client
    -- (other services, manual SQL, bugs).
    CONSTRAINT rooms_opening_hours_check CHECK (opens_at < closes_at)
);

CREATE UNIQUE INDEX rooms_name_idx ON rooms (lower(name));
