//! SeaORM entity for the `rooms` table (normally generated with `sea-orm-cli generate entity`).

use chrono::NaiveTime;
use sea_orm::entity::prelude::*;

// `DeriveEntityModel` generates from `Model`: `Entity` (the table), `Column` enum (one variant
// per field, used in filters), `PrimaryKey`, and `ActiveModel` (for inserts/updates).
// Columns not listed here (`created_at`) are simply not read or written.
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
#[sea_orm(table_name = "rooms")]
pub struct Model {
    // Ids are generated by the application (UUID v7), not by the database.
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: Uuid,
    pub name: String,
    pub description: Option<String>,
    pub capacity: i32,
    pub opens_at: NaiveTime,
    pub closes_at: NaiveTime,
}

// No relations used in this example (bookings stay with sqlx).
#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

// Hooks (before_save, after_save...) – default behaviour.
impl ActiveModelBehavior for ActiveModel {}
