//! `RoomRepository` implemented with Diesel + diesel-async (step 017, cargo feature `orm-diesel`).
//!
//! Diesel: mature ORM / query builder with the strongest compile-time guarantees – the schema is
//! described in Rust (`schema.rs`, normally generated by `diesel print-schema`) and every query is
//! type-checked against it WITHOUT a database at compile time.
//! Diesel itself is synchronous; `diesel-async` provides async connections (tokio-postgres
//! underneath) and connection pools (deadpool / bb8 / mobc).

mod schema;

use async_trait::async_trait;
use chrono::NaiveTime;
use diesel::{
    prelude::*,
    result::{DatabaseErrorKind, Error as DieselError},
};
use diesel_async::{
    AsyncPgConnection, RunQueryDsl,
    pooled_connection::{AsyncDieselConnectionManager, deadpool::Pool},
};
use uuid::Uuid;

use self::schema::rooms;
use crate::{
    config::DatabaseSettings,
    domain::{
        pagination::{Page, PageRequest},
        repositories::{RepositoryError, RepositoryResult, RoomRepository},
        room::{NewRoom, Room, RoomFilter},
    },
    infrastructure::postgres::{like_pattern, room_from_columns, to_db_int},
};

/// Row as loaded by Diesel.
// `Queryable` – build from a result row (fields in column order);
// `Selectable` + `as_select()` – generates the explicit column list from this struct.
// `check_for_backend` – compile-time check that field types match the schema for PostgreSQL.
#[derive(Queryable, Selectable)]
#[diesel(table_name = rooms)]
#[diesel(check_for_backend(diesel::pg::Pg))]
struct RoomRecord {
    id: Uuid,
    name: String,
    description: Option<String>,
    capacity: i32,
    opens_at: NaiveTime,
    closes_at: NaiveTime,
}

/// Values written by INSERT / UPDATE.
// `Insertable` – INSERT INTO rooms (...); `AsChangeset` – UPDATE rooms SET ...
// `treat_none_as_null` – by default `None` in a changeset means "don't touch the column";
// for a full replacement (PUT) `None` must write NULL.
#[derive(Insertable, AsChangeset)]
#[diesel(table_name = rooms)]
#[diesel(treat_none_as_null = true)]
struct RoomValues<'a> {
    name: &'a str,
    description: Option<&'a str>,
    capacity: i32,
    opens_at: NaiveTime,
    closes_at: NaiveTime,
}

impl<'a> From<&'a NewRoom> for RoomValues<'a> {
    fn from(room: &'a NewRoom) -> Self {
        Self {
            name: room.name.as_str(),
            description: room.description.as_deref(),
            capacity: to_db_int(room.capacity),
            opens_at: room.opening_hours.opens_at(),
            closes_at: room.opening_hours.closes_at(),
        }
    }
}

fn to_domain(record: RoomRecord) -> RepositoryResult<Room> {
    room_from_columns(
        record.id,
        &record.name,
        record.description,
        record.capacity,
        record.opens_at,
        record.closes_at,
    )
}

fn map_error(error: DieselError) -> RepositoryError {
    if let DieselError::DatabaseError(DatabaseErrorKind::UniqueViolation, _) = error {
        return RepositoryError::Conflict("a room with this name already exists".to_string());
    }
    RepositoryError::unexpected("diesel operation failed", error)
}

/// Dynamic WHERE clause shared by the page query and the count query.
// `into_boxed()` – erases the concrete query type so conditions can be added conditionally
// (each `.filter()` would otherwise produce a new, different type).
fn filtered(filter: &RoomFilter) -> rooms::BoxedQuery<'static, diesel::pg::Pg> {
    let mut query = rooms::table.into_boxed();
    if let Some(min) = filter.min_capacity {
        query = query.filter(rooms::capacity.ge(to_db_int(min)));
    }
    if let Some(name) = &filter.name {
        query = query.filter(rooms::name.ilike(like_pattern(name)));
    }
    query
}

pub struct DieselRoomRepository {
    // diesel-async can't use the sqlx pool – it needs its own (deadpool) pool of connections.
    pool: Pool<AsyncPgConnection>,
}

impl DieselRoomRepository {
    pub fn connect(settings: &DatabaseSettings) -> anyhow::Result<Self> {
        let manager = AsyncDieselConnectionManager::<AsyncPgConnection>::new(&settings.url);
        let pool = Pool::builder(manager)
            .max_size(settings.max_connections as usize)
            .build()?;
        Ok(Self { pool })
    }

    async fn connection(
        &self,
    ) -> RepositoryResult<diesel_async::pooled_connection::deadpool::Object<AsyncPgConnection>>
    {
        self.pool
            .get()
            .await
            .map_err(|e| RepositoryError::unexpected("diesel pool error", e))
    }
}

#[async_trait]
impl RoomRepository for DieselRoomRepository {
    async fn find(&self, filter: &RoomFilter, page: PageRequest) -> RepositoryResult<Page<Room>> {
        let mut conn = self.connection().await?;

        let records = filtered(filter)
            .order(rooms::id.asc())
            .limit(i64::from(page.size()))
            .offset(i64::try_from(page.offset()).unwrap_or(i64::MAX))
            .select(RoomRecord::as_select())
            // `load` (from `diesel_async::RunQueryDsl`) – the async counterpart of Diesel's `load`.
            .load(&mut conn)
            .await
            .map_err(map_error)?;

        let total: i64 = filtered(filter)
            .select(diesel::dsl::count_star())
            .get_result(&mut conn)
            .await
            .map_err(map_error)?;

        Ok(Page {
            items: records
                .into_iter()
                .map(to_domain)
                .collect::<Result<_, _>>()?,
            request: page,
            total: u64::try_from(total).unwrap_or_default(),
        })
    }

    async fn find_by_id(&self, id: Uuid) -> RepositoryResult<Option<Room>> {
        let mut conn = self.connection().await?;
        rooms::table
            .find(id)
            .select(RoomRecord::as_select())
            .first(&mut conn)
            .await
            // `optional()` – `NotFound` error -> `Ok(None)`.
            .optional()
            .map_err(map_error)?
            .map(to_domain)
            .transpose()
    }

    async fn insert(&self, new_room: NewRoom) -> RepositoryResult<Room> {
        let mut conn = self.connection().await?;
        let record = diesel::insert_into(rooms::table)
            // A tuple combines the generated id with the `Insertable` struct.
            .values((rooms::id.eq(Uuid::now_v7()), RoomValues::from(&new_room)))
            .returning(RoomRecord::as_returning())
            .get_result(&mut conn)
            .await
            .map_err(map_error)?;
        to_domain(record)
    }

    async fn update(&self, id: Uuid, data: NewRoom) -> RepositoryResult<Option<Room>> {
        let mut conn = self.connection().await?;
        diesel::update(rooms::table.find(id))
            .set(RoomValues::from(&data))
            .returning(RoomRecord::as_returning())
            .get_result(&mut conn)
            .await
            .optional()
            .map_err(map_error)?
            .map(to_domain)
            .transpose()
    }

    async fn delete(&self, id: Uuid) -> RepositoryResult<bool> {
        let mut conn = self.connection().await?;
        let deleted = diesel::delete(rooms::table.find(id))
            .execute(&mut conn)
            .await
            .map_err(map_error)?;
        Ok(deleted > 0)
    }
}
